Repository canonical/smtp-integrator-operator, pull requests merged in 2023-10, with the labels that each got.

#1 Minimal working charm
  .woke.yaml
  charmcraft.yaml
  config.yaml
  lib/charms/smtp_integrator/v0/smtp.py
  metadata.yaml
  pyproject.toml
  requirements.txt
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src/charm.py
  src/charm_state.py
  tests/integration/any_charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_base.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_library_smtp.py
  tox.ini
Labels: complex, Libraries: Out of sync

#3 Fix release pipeline
  .github/workflows/publish_charm.yaml
Labels: Libraries: Out of sync, trivial

#4 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: Out of sync, trivial

#7 Secrets support
  .github/workflows/integration_test.yaml
  .github/workflows/publish_charm.yaml
  README.md
  docs/explanation/charm-architecture.md
  docs/how-to/configure-smtp.md
  docs/how-to/contribute.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/integrations.md
  docs/tutorial/getting-started.md
  lib/charms/smtp_integrator/v0/smtp.py
  metadata.yaml
  pyproject.toml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src/charm.py
  src/charm_state.py
  tests/integration/any_charm.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_library_smtp.py
  tox.ini
Labels: complex, Libraries: Out of sync

#9 Juju 2 support
  .github/workflows/integration_test.yaml
  metadata.yaml
  src/charm.py
  tests/unit/test_charm.py
  tox.ini
Labels: Libraries: OK, trivial

#15 Return enums instead of strings when accessing the relation data
  lib/charms/smtp_integrator/v0/smtp.py
Labels: Libraries: Out of sync, trivial

#16 Recreate smtp lib
  lib/charms/smtp_integrator/v0/smtp.py
Labels: Libraries: Out of sync, trivial

#17 Recreate smtp lib
  lib/charms/smtp_integrator/v0/smtp.py
Labels: Libraries: Out of sync, trivial

#18 Use python3.8 syntax in the smtp library
  lib/charms/smtp_integrator/v0/smtp.py
Labels: Libraries: Out of sync, trivial
